/**
 * Builds sitemap.xml from the pages that actually exist.
 *
 *   npm run sitemap        (from the _developer folder)
 *
 * A page is listed when it has a canonical URL and is not marked noindex, so
 * adding, removing or un-noindexing a page is picked up automatically. Each
 * entry's lastmod is the date the page file was last changed.
 */
const fs = require('fs');
const path = require('path');

const SITE = path.resolve(__dirname, '..', '..');
const SKIP_DIRS = new Set(['_developer', 'assets', 'node_modules']);

const pages = [];
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) walk(full);
    } else if (entry.name === 'index.html') {
      pages.push(full);
    }
  }
})(SITE);

const listed = [];
const skipped = [];

for (const file of pages) {
  const html = fs.readFileSync(file, 'utf8');
  const rel = path.relative(SITE, file).split(path.sep).join('/');
  const robots = (html.match(/<meta\s+name="robots"\s+content="([^"]*)"/i) || [])[1] || '';
  const canonical = (html.match(/<link\s+rel="canonical"\s+href="([^"]*)"/i) || [])[1];

  if (/noindex/i.test(robots)) { skipped.push(`${rel} (noindex)`); continue; }
  if (!canonical) { skipped.push(`${rel} (no canonical)`); continue; }

  const lastmod = fs.statSync(file).mtime.toISOString().slice(0, 10);
  // Home first, then shallow pages before deeper ones, then alphabetical.
  const depth = new URL(canonical).pathname.split('/').filter(Boolean).length;
  listed.push({ loc: canonical, lastmod, depth });
}

listed.sort((a, b) => a.depth - b.depth || a.loc.localeCompare(b.loc));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by _developer/scripts/build-sitemap.cjs. Run "npm run sitemap" after adding or removing pages.
     A page is listed when it has a canonical URL and is not marked noindex. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${listed.map((p) => `  <url><loc>${p.loc}</loc><lastmod>${p.lastmod}</lastmod></url>`).join('\n')}
</urlset>
`;

fs.writeFileSync(path.join(SITE, 'sitemap.xml'), xml);
console.log(`sitemap.xml written: ${listed.length} URLs`);
listed.forEach((p) => console.log(`  + ${p.loc}`));
if (skipped.length) {
  console.log('left out:');
  skipped.forEach((s) => console.log(`  - ${s}`));
}
